---
title: "TimeSeriesAnalysis"
author: "Syd Kamath"
date: "2024-05-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
install.packages("PerformanceAnalytics", repos = "http://cran.us.r-project.org")
install.packages("rugarch", repos = "http://cran.us.r-project.org")

library(forecast)
library(quantmod)
library(PerformanceAnalytics)
library(rugarch)
```

## Data pre-processing (S & P 500)

```{r}
today <- Sys.Date()

data <- getSymbols("^GSPC", auto.assign=FALSE, from="1980-01-01",
to=today)$GSPC.Adjusted
ret.data <- na.omit(Return.calculate(data, method="log"))
ret_pre_2008 <- ret.data["2006-01-01::2008-01-01"]
ret_2008 <- ret.data["2008-01-07::2009-01-01"]
ret_post_crash <- ret.data["2009-01-02::2020-03-13"]
ret_black_mon <- ret.data["2020-03-16"]
ret_post_black_mon <- ret.data["2020-03-30::2024-05-09"]
print(length(ret_pre_2008))
```

## GARCH time series forecast comparisons:

Same order, different error distributions

```{r}
orders <- c("(0,1)","(1,1)", "(2,1)", "(3,1)", "(4,1)") 
df <- data.frame(
  Order = orders,
  GED = c(0,0,0,0,0),
  SSTD = c(0,0,0,0,0),
  Norm = c(0,0,0,0,0)
)
# Generalized Extreme Distribution
# for (i in 0:4) {
#   spec1 <- ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1,1)),
#                     mean.model = list(armaOrder = c(i,1), include.mean = TRUE),
#                     distribution.model = "ged")
#   fit1.armagarch <- ugarchfit(data=ret_pre_2008,spec=spec1)
#   df$GED[i + 1] <- infocriteria(fit1.armagarch)[1]
# }

# garch on pre 2008 data
spec1 <- ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1,1)),
                    mean.model = list(armaOrder = c(2,1), include.mean = TRUE),
                    distribution.model = "ged")
fit1.armagarch <- ugarchfit(data=ret_pre_2008,spec=spec1)
fit1.predict <- ugarchforecast(fit1.armagarch,n.ahead=30)
plot(fit1.armagarch,which=2)

# garch on 2008 data, same parameters as above with expected value
fit2.armagarch <- ugarchfit(data=ret_2008,spec=spec1)
fit2.predict <- ugarchforecast(fit2.armagarch,n.ahead=30)
sim <- ugarchsim(fit2.armagarch,n.sim=1000,n.start=1,m.sim=10,startMethod="sample")
plot(fit2.armagarch,which=2)

#plot(fit1.armagarch,which=9)
#plot(fit1.armagarch,which=10)
#plot(fit1.armagarch,which=11)

#plot(fit2.armagarch,which=9)
#plot(fit2.armagarch,which=10)
#plot(fit2.armagarch,which=11)
```

# ARIMA forecast with simulated path

```{r}
model <- auto.arima(ret_pre_2008)
print(model)
arima.fit <- Arima(ret_pre_2008,order=c(1,0,0),include.mean=TRUE,include.drift = TRUE)
arima.fc <- forecast(arima.fit,h=100)
plot(arima.fc)
sample_paths <- list()
for(i in seq(1,10000,by = 1)){
  path <- simulate(arima.fit,nsim=100,bootstrap=TRUE)
  sample_paths[i] <- list(c(path))
}

for(i in seq(1,2,by=1)){
  lines(x=seq(502,601,by=1),sample_paths[[i]],col="blue")
}

lines(x=seq(502,601,by=1),y=ret_2008[1:100],col="red")
qqnorm(arima.fc$residuals)
qqline(arima.fc$residuals)
checkresiduals(arima.fc)
```

# Forecasting of electricity prices (seasonality)

```{r message=FALSE, warning=FALSE}
install.packages("TSA",repos = "http://cran.us.r-project.org")
library(tseries)
```

Initial tests:

```{r}
data(electricity, package="TSA")
log.electricity <- log(electricity)
#plot(log.electricity)
log.elect.initial.fit <- auto.arima(log.electricity)
print(log.elect.initial.fit)

# stationarity test when accounting for seasonal differences
kpss.test(diff(log.electricity, lag=12))
adf.test(diff(log.electricity, lag=12))
pp.test(diff(log.electricity, lag=12))

checkresiduals(log.elect.initial.fit)
```

```{r}
log.elect.final.fit <- auto.arima(log.electricity,D=1,seasonal=TRUE,allowdrift=TRUE,allowmean=TRUE,max.P = 5, max.Q = 5,ic="aicc")
print(log.elect.final.fit)
checkresiduals(log.elect.final.fit)
```

```{r}
model <- Arima(electricity, order = c(4,0,3), seasonal=c(2,1,1),include.mean=TRUE,include.drift=TRUE)
Y <- forecast(model,h=24,level=c(80,95))
plot(Y)
```
